text = "HELLO worLD"
print(text.lower())

text = "my Name Is Noman"
print(text.lower())


text1 = "My univeRsity namE"
print(text.lower())


Text2 = "my Pet NaME Is Goldy"
print(Text2.isupper())

print("my pet name is tony".upper())

print("atomic habits".title())

text1 = "hELLO"
text2 = "nOMAN"
print((text1.swapcase()))
print(text2.swapcase())

Text3 = "nAME"
Text4 = "hASHIR"
print(Text3.swapcase())
print(Text4.swapcase())

Text5 = "    hello       "
print(Text5.strip())

Text = "       Peshawar        "
print(Text.strip())

Text = "pAKISTAN"
print(Text.swapcase())

Text2 = "my name is noman"
print(Text2.islower())


print("noman")